services:
  audio-http:
    image: nginx:alpine
    container_name: audio-http
    restart: unless-stopped
    ports:
      - "8765:80"
    volumes:
      - /mnt/nas/code_artifacts:/usr/share/nginx/html:ro
      - ../../files/nginx.conf:/etc/nginx/conf.d/default.conf:ro
