services:
  tutorials:
    build: ../../
    container_name: tutorials
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - tutorials-net

  audio-http:
    image: nginx:alpine
    container_name: audio-http
    restart: unless-stopped
    networks:
      - tutorials-net
    volumes:
      - /mnt/nas/code_artifacts:/usr/share/nginx/html:ro
      - ./nginx-audio.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  tutorials-net:
