server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /go-db-scheduler/audio/ {
        proxy_pass http://audio-http/tutorials/go-db-scheduler/audio/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /zabbix-webhooks-go/audio/ {
        proxy_pass http://audio-http/tutorials/zabbix-webhooks-go/audio/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
